/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_gcsc_vrl_ug4_UG4 */

#ifndef _Included_edu_gcsc_vrl_ug4_UG4
#define _Included_edu_gcsc_vrl_ug4_UG4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    createJavaBindings
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_gcsc_vrl_ug4_UG4_createJavaBindings
  (JNIEnv *, jobject);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    convertRegistryInfo
 * Signature: ()Ledu/gcsc/vrl/ug4/NativeAPIInfo;
 */
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug4_UG4_convertRegistryInfo
  (JNIEnv *, jobject);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    invokeMethod
 * Signature: (Ljava/lang/String;JZLjava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug4_UG4_invokeMethod
  (JNIEnv *, jobject, jstring, jlong, jboolean, jstring, jobjectArray);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    newInstance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_gcsc_vrl_ug4_UG4_newInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    getExportedClassPtrByName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_gcsc_vrl_ug4_UG4_getExportedClassPtrByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    invokeFunction
 * Signature: (Ljava/lang/String;Z[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug4_UG4_invokeFunction
  (JNIEnv *, jobject, jstring, jboolean, jobjectArray);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    ugInit
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_gcsc_vrl_ug4_UG4_ugInit
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    getSvnRevision
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug4_UG4_getSvnRevision
  (JNIEnv *, jobject);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    getCompileDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug4_UG4_getCompileDate
  (JNIEnv *, jobject);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    getMessages
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug4_UG4_getMessages
  (JNIEnv *, jobject);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    clearMessages
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_gcsc_vrl_ug4_UG4_clearMessages
  (JNIEnv *, jobject);

/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    setMaxQueueSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_gcsc_vrl_ug4_UG4_setMaxQueueSize
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_gcsc_vrl_ug4_UG4_MessageThread */

#ifndef _Included_edu_gcsc_vrl_ug4_UG4_MessageThread
#define _Included_edu_gcsc_vrl_ug4_UG4_MessageThread
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_gcsc_vrl_ug4_UG4_MessageThread_MIN_PRIORITY
#define edu_gcsc_vrl_ug4_UG4_MessageThread_MIN_PRIORITY 1L
#undef edu_gcsc_vrl_ug4_UG4_MessageThread_NORM_PRIORITY
#define edu_gcsc_vrl_ug4_UG4_MessageThread_NORM_PRIORITY 5L
#undef edu_gcsc_vrl_ug4_UG4_MessageThread_MAX_PRIORITY
#define edu_gcsc_vrl_ug4_UG4_MessageThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_gcsc_vrl_ug4_MemoryManager */

#ifndef _Included_edu_gcsc_vrl_ug4_MemoryManager
#define _Included_edu_gcsc_vrl_ug4_MemoryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_gcsc_vrl_ug4_MemoryManager
 * Method:    delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_gcsc_vrl_ug4_MemoryManager_delete
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
