/*
 * nestedNewtonRFSwitch.h
 *
 *  Created on: 27.07.2021
 *      Author: Markus Knodel
 */

#ifndef UGCORE_UGBASE_NESTEDNEWTONRFSWITCH_H_
#define UGCORE_UGBASE_NESTEDNEWTONRFSWITCH_H_

#ifndef ENABLE_NESTED_NEWTON_RESOLFUNC_UPDATE
#define ENABLE_NESTED_NEWTON_RESOLFUNC_UPDATE 0
#endif



#endif /* UGCORE_UGBASE_NESTEDNEWTONRFSWITCH_H_ */
