#!/bin/bash
######################################################################
# cdug 1.0
#-------------------------------------------------------------------
# author: Stefan Grein, Martin Rupp
######################################################################


function cdug() {
  cd $UG4_ROOT/$1
   
}

cdug_complete() {
  local word="${COMP_WORDS[COMP_CWORD]}"
  local i=0
  while read line; do
  	[[ -d $line ]] && COMPREPLY[i++]=`echo $line | sed -n "s?$UG4_ROOT[/]*??p"`/;
  	done < <(compgen -f -- "$UG4_ROOT/$word")  
}

SHELLTYPE=`ps -hp $$`
if [[ "$SHELLTYPE" = *bash* ]]; then
	complete -F cdug_complete -o nospace cdug
fi
