#!/bin/bash
######################################################################
# clusters
#-------------------------------------------------------------------
# created by Martin Rupp 28.03.2012
# this file is used by ugsubmit/ugcancel/uginfo to access all clusters
# see below for information how to add your own cluster implementation
######################################################################

#cekon 			slurm+mpirun 	1 	92
#hermit 		qsub+aprun 		32 	65536
#NecNehalem		qsub+mpirun		4	1024
#Jugene			LL+mpirun		4	65536


if [ -z "$UGSUBMIT_TYPE" ]; then
	if [ $HOSTNAME == "cekon.gcsc.uni-frankfurt.de" ]; then
		UGSUBMIT_TYPE=cekon
	elif [ $HOSTNAME == "cesari.gcsc.uni-frankfurt.de" ]; then
		UGSUBMIT_TYPE=cesari
	else
	    #echo $HOSTNAME
   		echo "please set UGSUBMIT_TYPE or specify cluster with -cluster".
   		exit
   	fi   	
fi	 

if [ $UGSUBMIT_TYPE == "Hermit" ] || [ $UGSUBMIT_TYPE == "NecNehalem" ]; then

	source $scriptpath/schedulers/hermit
	
elif [ $UGSUBMIT_TYPE == "Jugene" ]; then

	source $scriptpath/schedulers/jugene
	
elif [ $UGSUBMIT_TYPE == "Juqueen" ]; then
	source $scriptpath/schedulers/juqueen
elif [ $UGSUBMIT_TYPE == "mpi" ]; then

	source $scriptpath/schedulers/mpi
	
elif [ $UGSUBMIT_TYPE == "cekon" ]; then

	source $scriptpath/schedulers/cekon
	
elif [ $UGSUBMIT_TYPE == "cesari" ]; then

	source $scriptpath/schedulers/cesari
	
elif [ $UGSUBMIT_TYPE == "moab" ]; then
	source $scriptpath/schedulers/moab
############################################################
#
# you can add your own cluster like this:
#
#elif [ $UGSUBMIT_TYPE == "mycluster" ]; then
#	source $scriptpath/schedulers/mycluster
#
# use the schedulers/new_template template file for this
############################################################
	
else
	echo "" 
	echo "ERROR: cluster "$UGSUBMIT_TYPE" is not supported."
	exit
fi
