#!/bin/bash
# parameter1: path to get svn revision of
# parameter2: path and name of output file


# git commit info
GIT_REVISION="unknown"
echo "${1}/.git"
if [[ -d "${1}/.git" ]]; then
	GIT_REVISION=$(git -C "${1}" rev-parse --short HEAD)
fi

HOSTNAME=`hostname`
if [[ ! $? == 0 ]]; then
   HOSTNAME="unknown"
fi

COMPILE_DATE=`date`
cat > $2 <<EOF
namespace ug{
const char *UG_GIT_REVISION="$GIT_REVISION";
const char *UG_BUILD_HOST="$HOSTNAME";
const char *UG_COMPILE_DATE="$COMPILE_DATE";
// ${1}/.git
}
EOF
