#!/bin/bash
# parameter1: path to get svn revision of
# parameter2: path and name of output file
SVN_REVISION=`svnversion $1`
if [[ ! $? == 0 ]]; then
   SVN_REVISION="unknown"
fi
HOSTNAME=`hostname`
if [[ ! $? == 0 ]]; then
   HOSTNAME="unknown"
fi
COMPILE_DATE=`date`
cat > $2 <<EOF
namespace ug{
const char *SVN_REVISION="$SVN_REVISION";
const char *BUILD_HOST="$HOSTNAME";
const char *COMPILE_DATE="$COMPILE_DATE";
}
EOF
