#!/bin/bash
######################################################################
# ugbash
#-------------------------------------------------------------------
# created by Martin Rupp 01.06.2012
# mail: martin.rupp@gcsc.uni-frankfurt.de
#
# source this file in your ~/.bashrc :
# 1. with specifiying UG4_ROOT:
# UG4_ROOT=~/Documents/workspace/ug4
# source $UG4_ROOT/scripts/shell/ugbash
# 2. without (UG4_ROOT is set to the path ../../ of ugbash)
# source ~/Documents/workspace/ug4/scripts/ugbash
#
# by that, you can access all ug4 bash scripts:
# cdug - change ug4 directory
# ugsubmit/uginfo/ugcancel - Unified Job Scheduling Scripts, see ugsubmit
# uginstall - install local versions of software (for advanced users)
# bash completion for ugshell, cmake, ugcmake, and all of the above 
######################################################################

#     get UG4_ROOT     # 
########################

if [ -z "$UG4_ROOT" ]; then
	UG4_ROOT=`dirname ${BASH_SOURCE[0]}`/../../
	
	# make path absolute
	# for compatibilty to mac, don't use realpath or readlink here.
	olddir=`pwd`
	cd $UG4_ROOT
	UG4_ROOT=`pwd`
	cd $olddir
else
	if [ ! -e $UG4_ROOT/cmake/ug_includes.cmake ]; then
		echo "Could not find UG4_ROOT/cmake/ug_includes.cmake . Is UG4_ROOT=$UG4_ROOT right?"
	fi	   	
fi	

export UG4_ROOT

# add scripts/shell to path
PATH=$PATH:$UG4_ROOT/scripts/shell:$UG4_ROOT/bin
export PATH

# add ugcomplete and cdug (for bash only)
SHELLTYPE=`ps -o comm="" -p $$`
case "$SHELLTYPE" in
	*bash*) source $UG4_ROOT/scripts/shell/ugcomplete
	;;
esac
source $UG4_ROOT/scripts/shell/cdug

# make bash scripts executable
chmod +x $UG4_ROOT/scripts/shell/uginfo
chmod +x $UG4_ROOT/scripts/shell/ugcancel
chmod +x $UG4_ROOT/scripts/shell/ugsubmit

chmod +x $UG4_ROOT/scripts/shell/uginstall
chmod +x $UG4_ROOT/scripts/shell/sshfsmake

chmod +x $UG4_ROOT/scripts/shell/xprun
chmod +x $UG4_ROOT/scripts/shell/mpigdb1
chmod +x $UG4_ROOT/scripts/shell/xtermrun

chmod +x $UG4_ROOT/scripts/shell/ugcmake-start
chmod +x $UG4_ROOT/scripts/shell/ugconfig

ugbasegrep()
{
	fgrep --exclude-dir=".svn" -rI "$1" $UG4_ROOT/ugbase
}
ugpluginsgrep()
{
	fgrep --exclude-dir=".svn" -rI "$1" $UG4_ROOT/plugins
}
ugcmakegrep()
{
	fgrep --exclude-dir=".svn" -rI "$1" $UG4_ROOT/cmake
}

ugappsgrep()
{
	fgrep --include="*\.lua" --exclude="ug4CompletionList.txt" --exclude="myUg4CompletionList.txt" \
		--include="*\.c" --include="*\.cpp" --include="*\.txt" --include="*\.h" -rI "$1" $UG4_ROOT/apps
}

ugscriptsgrep()
{
	fgrep --include="*\.lua" --include="*\.c" --include="*\.cpp" --include="*\.txt"--include="*\.h" \
		-rI "$1" $UG4_ROOT/scripts
}

uggrep()
{
	fgrep --include="*\.lua" --include="*\.c*" --include="*\.h" --include="*\.txt" --exclude-dir=".svn" \
		--exclude="ug4CompletionList.txt" --exclude="myUg4CompletionList.txt" -rI "$1" $UG4_ROOT
}

ugdocsgrep()
{
	fgrep --include="*\.doxygen" --exclude-dir=".svn" -rI "$1" $UG4_ROOT/docs
}

ug4svnupdate()
{
	cd $UG4_ROOT
	svn update
	cd -
}

ugclearoutput()
{
	find . -name '*.pmat' | xargs rm
	find . -name '*.mat' | xargs rm
	find . -name '*.pvec' | xargs rm
	find . -name '*.vec' | xargs rm
	find . -name '*.pvtu' | xargs rm
	find . -name '*.vtu' | xargs rm
	find . -name '*.values' | xargs rm
	find . -name '*.marks' | xargs rm
	find . -name '*.ugx' | xargs rm
}

alias ugrelib="rm $UG4_ROOT/lib/*; rm $UG4_ROOT/bin/ugshell; rm $UG4_ROOT/bin/plugins/*"

scriptpath=`dirname ${BASH_SOURCE:-$0}`
source $scriptpath/uginstall_config

