#!/bin/bash
# created by Martin Rupp 05.03.2012
# authors: Martin Rupp, Andreas Vogel, Arne Naegel.

##### 1. read parameters, set cpus (or exit) ########
#####################################################

# set default values
scriptname=$0;		  # name of script

echo "ugcancel 0.1. (c) Goethe-Center for Scientific Computing 2012"

function usage 
{
	echo ""
    echo " usage:  "$scriptname" <jobid> [-cluster <clustertype>]..."
	echo " "
	echo "        <jobid>                : jobib (use uginfo to get a jobid)"
	echo ""
    exit 0;
}

# check that at least 2 args given, else print usage
if [ $# -lt 1 ]; then
   usage
fi

jobid=$1;            # number of nodes
shift

while [  $# -gt 0 ]
do
	if [ $1 = "-cluster" ]; then
		UGSUBMIT_TYPE=$2
		shift 2
	else
		break
	fi
done

if [ -z "$UGSUBMIT_TYPE" ]; then
   	echo "please set UGSUBMIT_TYPE or specify cluster with -cluster".
   	exit
fi	 

##############################################
if [ $UGSUBMIT_TYPE = "NecNehalem" ]; then
echo "Using NecNehalem"
qdel $jobid

elif [ $UGSUBMIT_TYPE = "Hermit" ]; then
echo "Using Hermit"
qdel $jobid

##############################################
elif [ $UGSUBMIT_TYPE = "Jugene" ]; then
echo "Using Jugene"

##############################################
elif [ $UGSUBMIT_TYPE = "mpi" ]; then
echo "Using MPI"
kill $jobid

##############################################
elif [ $UGSUBMIT_TYPE = "cekon" ]; then
echo "Using SLURM on cekon"
scancel $jobid

##############################################
else
	echo "" 
	echo "ERROR: cluster "$UGSUBMIT_TYPE" is not supported."
fi



