#!/bin/bash
######################################################################
# ugbash
#-------------------------------------------------------------------
# created by Martin Rupp 01.07.2014
# mail: martin.rupp@gcsc.uni-frankfurt.de
#
# call this file instead of cmake .. when configuring on a cluster
# it will automatically call cmake with the right toolchain
# it can also be used to check compiler modules etc.
# see also ugconfig.
######################################################################

	
if [ -z "$UGSUBMIT_TYPE" ]; then
	if [ -z "$UGSUBMIT_TYPE" ]; then
		if [ $HOSTNAME == "cekon.gcsc.uni-frankfurt.de" ]; then
			UGSUBMIT_TYPE=cekon
		elif [ $HOSTNAME == "cesari.gcsc.uni-frankfurt.de" ]; then
			UGSUBMIT_TYPE=cesari
		elif [[ "$HOSTNAME" == "juqueen"* ]]; then
			UGSUBMIT_TYPE=Juqueen
		else
			unamestr=`uname`
			if [[ "$unamestr" == 'Darwin' ]]; then
				UGSUBMIT_TYPE=Apple
			else
			    #echo $HOSTNAME
		   		echo "please set UGSUBMIT_TYPE or specify cluster with -cluster".
		   		exit
		   	fi
	   	fi   	
	fi	 	
fi	 


if [ $UGSUBMIT_TYPE == "Hermit" ]; then
	echo "ugcmake-start: on Hermit. calling cmake with toolchain file."
	echo "ugcmake-start: also make sure LAPACK and BLAS modules are loaded (see also ugconfig)"
	echo "ugcmake-start: Listing Modules:"
	module list		
	echo "ugcmake-start: cmake -DCMAKE_TOOLCHAIN_FILE=$UG4_ROOT/cmake/toolchain/hermit.cmake $*"
	cmake -DCMAKE_TOOLCHAIN_FILE=$UG4_ROOT/cmake/toolchain/hermit.cmake $*		
elif [ $UGSUBMIT_TYPE == "cekon" ]; then
	echo "ugcmake-start: on Cekon: cmake $*"
	cmake $* ..
elif [ $UGSUBMIT_TYPE == "cesari" ]; then
	echo "ugcmake-start: on Cekon: cmake $*"
	cmake $* ..		
elif [[ $UGSUBMIT_TYPE == "Juqueen" ]]; then
	echo "ugcmake-start: on Juqueen. calling cmake with toolchain file."
	echo "ugcmake-start: cmake -DSTATIC_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=$UG4_ROOT/cmake/toolchain/juqueen.cmake $*"
	cmake -DSTATIC_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=$UG4_ROOT/cmake/toolchain/juqueen.cmake $*
elif [[ $UGSUBMIT_TYPE == "Apple" || $UGSUBMIT_TYPE == "mpi" ]]; then
	echo "ugcmake-start: on Apple: cmake $*"
	cmake $*
else
    #echo $HOSTNAME
	echo "ugcmake-start: cluster could not be auto-detected or is not known. please set UGSUBMIT_TYPE.".
	exit
fi   	

