#!/bin/bash
######################################################################
# ugbash
#-------------------------------------------------------------------
# created by Martin Rupp 01.07.2014
# mail: martin.rupp@gcsc.uni-frankfurt.de
#
# source this file in your ~/.bashrc .
# it will then automatically set up the cluster for ug4
# e.g. loading of lapack/blas/compiler modules.
######################################################################


if [ -z "$UGSUBMIT_TYPE" ]; then
	if [ -z "$UGSUBMIT_TYPE" ]; then
		if [ $HOSTNAME == "cekon.gcsc.uni-frankfurt.de" ]; then
			UGSUBMIT_TYPE=cekon
		elif [ $HOSTNAME == "cesari.gcsc.uni-frankfurt.de" ]; then
			UGSUBMIT_TYPE=cesari
		elif [[ "$HOSTNAME" == "juqueen"* ]]; then
			UGSUBMIT_TYPE=Juqueen
		else
			unamestr=`uname`
			if [[ "$unamestr" == 'Darwin' ]]; then
				UGSUBMIT_TYPE=Apple
			else
			    #echo $HOSTNAME
			    echo "Hello, this is ugconfig trying to config your cluster"
		   		echo "please set UGSUBMIT_TYPE or specify cluster with -cluster".
		   		exit
		   	fi
	   	fi   	
	fi
	echo "ugconfig: Configuring your bash environment... Your auto-detected cluster is $UGSUBMIT_TYPE."
else
	echo "ugconfig: Configuring your bash environment... Your selected cluster is $UGSUBMIT_TYPE."	 	
fi	 



if [ $UGSUBMIT_TYPE == "Hermit" ]; then
	echo "ugconfig: On Hermit, loading gnu compilers" 
	module list 2>&1 | grep PrgEnv-gnu > /dev/null
	if [ $? == 1 ]; then
	echo loading PrgEnv-gnu
	module swap $(module li 2>&1 | awk '/PrgEnv/{print $2}') PrgEnv-gnu
	else
	echo PrgEnv-gnu already loaded.
	fi
	
elif [ $UGSUBMIT_TYPE == "cekon" ]; then
	echo "ugconfig: Nothing to configure on cekon. Have a nice day."
	
elif [ $UGSUBMIT_TYPE == "cesari" ]; then
	echo "ugconfig: Nothing to configure on cesari. Have a nice day."
			
elif [[ $UGSUBMIT_TYPE == "Apple" || $UGSUBMIT_TYPE == "mpi" ]]; then
	echo "ugconfig: Nothing to configure on $UGSUBMIT_TYPE. Have a nice day."
	
elif [[ $UGSUBMIT_TYPE == "Juqueen" ]]; then
	echo "ugconfig: On Juqueen, loading cmake and lapack."
	module load cmake
	module load lapack
	
else
    #echo $HOSTNAME
	echo "ugconfig: not yet supported cluster".
fi   	

