#!/bin/bash
LOCAL_INSTALLDIR=$HOME/local
# LIBRARY_PATH is used by gcc before compilation to search for directories
#              containing libraries that need to be linked to your program.
# LD_LIBRARY_PATH is used by your program to search for directories containing 
#                 the libraries after it has been successfully compiled and linked
my_setup()
{
	dir=$1
	if [ -e $dir ]; then
		#echo $dir found!
		if [ -e $dir/lib ]; then
			if [ -z $LIBRARY_PATH ]; then
				LIBRARY_PATH=$dir/lib64:$dir/lib
			else
				echo $LIBRARY_PATH | grep -q $dir/lib
				if [ $? -ne 0 ] ; then
					LIBRARY_PATH=$LIBRARY_PATH:$dir/lib64:$dir/lib
				fi
			fi
			if [ -z $LD_LIBRARY_PATH ]; then
				LD_LIBRARY_PATH=$dir/lib64:$dir/lib
			else
				echo $LD_LIBRARY_PATH | grep -q $dir/lib
				if [ $? -ne 0 ] ; then
					LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$dir/lib64:$dir/lib
				fi
			fi
			if [ -z $LD_RUN_PATH ]; then
				echo $LD_RUN_PATH | grep -q $dir/lib
				if [ $? -ne 0 ] ; then
					LD_RUN_PATH=$dir/lib64:$dir/lib
				fi
			else		
				LD_RUN_PATH=$LD_RUN_PATH:$dir/lib64:$dir/lib
			fi
			
			echo $LDFLAGS | grep -q $dir/lib
			if [ $? -ne 0 ] ; then
				LDFLAGS="-L$dir/lib $LDFLAGS"
			fi
			echo $LDFLAGS | grep -q $dir/lib64
			if [ $? -ne 0 ] && [ -e $dir/lib64 ]; then
				LDFLAGS="-L$dir/lib64 $LDFLAGS"
			fi

		fi
		if [ -e $dir/include ]; then
			if [ -z $C_INCLUDE_PATH ]; then
				C_INCLUDE_PATH=$dir/include/
			else
				echo $C_INCLUDE_PATH | grep -q $dir/include
				if [ $? -ne 0 ] ; then
					C_INCLUDE_PATH="$dir/include:$C_INCLUDE_PATH"
				fi
			fi
			if [ -z $CPLUS_INCLUDE_PATH ]; then
				CPLUS_INCLUDE_PATH="$dir/include"
			else
				echo $CPLUS_INCLUDE_PATH | grep -q $dir/include
				if [ $? -ne 0 ] ; then
					CPLUS_INCLUDE_PATH=$dir/include:$CPLUS_INCLUDE_PATH
				fi
			fi	
		fi
		
		if [ -e $dir/bin ]; then
			echo $PATH | grep -q $dir/bin
			if [ $? -ne 0 ] ; then
				PATH=$dir/bin:$PATH
			fi
		fi
	fi
}

my_setup2 () 
{
	local name=$1
	local dir=$LOCAL_INSTALLDIR/$name/used
	my_setup $dir
	
}

my_setup llvm
my_setup2 cmake
my_setup2 doxygen
my_setup2 gcc
my_setup2 gmp
my_setup2 gnuplot
my_setup2 GotoBLAS2
my_setup2 mpfr
my_setup2 mpc
my_setup $LOCAL_INSTALLDIR/openmpi/1.6
my_setup2 ParaView



export PATH
export C_INCLUDE_PATH	
export CPLUS_INCLUDE_PATH
export LD_RUN_PATH
export LD_LIBRARY_PATH
export LIBRARY_PATH
export LDFLAGS
