#!/bin/bash
# created by Martin Rupp 05.03.2012

echo "ugjobinfo"
echo "-------------------------------------------------"
echo "(c) Goethe-Center for Scientific Computing 2012"

function usage 
{
	echo ""
    exit 0;
}

while [ $# -gt 0 ]
do
	if [ $1 = "-so" ]; then
		scheduleroptions=$2
		shift 2
	elif [ $1 = "-cluster" ]; then
		UGSUBMIT_TYPE=$2
		shift 2
	else
		cont=false
		break
	fi
done

##############################################
if [ $UGSUBMIT_TYPE = "NecNehalem" ]; then
	echo "Using qsub on NecNehalem / NEC Nehalem Cluster / HLRS"
echo "Using NecNehalem"
qstat | sed -n 1p
qstat | grep $USER	

elif [ $UGSUBMIT_TYPE = "Hermit" ]; then
echo "Using Hermit"
qstat | sed -n 1p
qstat | grep $USER

##############################################
elif [ $UGSUBMIT_TYPE = "Jugene" ]; then
echo "Using Jugene"

##############################################
elif [ $UGSUBMIT_TYPE = "mpi" ]; then
echo "Using MPI"
ps aux | sed -n 1p
ps aux | grep $USER | grep mpirun

##############################################
elif [ $UGSUBMIT_TYPE = "cekon" ]; then
echo "Using SLURM on cekon"
squeue | sed -n 1p
squeue | grep $USER

##############################################
else
	echo "" 
	echo "ERROR: cluster "$UGSUBMIT_TYPE" is not supported."
fi



