#!/bin/bash
######################################################################
# uginstall_config
#-------------------------------------------------------------------
# created by Martin Rupp 31.05.2012
# mail: martin.rupp@gcsc.uni-frankfurt.de
######################################################################
# This file sets all environment variables for uginstall
# these are
# - LIBRARY_PATH
# - LD_LIBRARY_PATH
# - LDFLAGS
# - PATH
# - C_INCLUDE_PATH
# - CPLUS_INCLUDE_PATH
# without this file, uginstall won't work!

LOCAL_INSTALLDIR=$HOME/local


# LIBRARY_PATH is used by gcc before compilation to search for directories
#              containing libraries that need to be linked to your program.
# LD_LIBRARY_PATH is used by your program to search for directories containing 
#                 the libraries after it has been successfully compiled and linked
add_lib()
{
	lib=$1
	if [ -e $lib ]; then

	if [ -z $LIBRARY_PATH ]; then
		LIBRARY_PATH=$lib
	else
		echo $LIBRARY_PATH | grep -q $lib
		if [ $? -ne 0 ] ; then
			LIBRARY_PATH=$LIBRARY_PATH:$lib
		fi
	fi

	if [ -z $LD_LIBRARY_PATH ]; then
		LD_LIBRARY_PATH=$lib
	else
		echo $LD_LIBRARY_PATH | grep -q $lib
		if [ $? -ne 0 ] ; then
			LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$lib
		fi
	fi

	if [ -z $LD_RUN_PATH ]; then
		LD_RUN_PATH=$lib
	else
		echo $LD_RUN_PATH | grep -q $lib
		if [ $? -ne 0 ] ; then
			LD_RUN_PATH=$LD_RUN_PATH:$lib
		fi
	fi

	echo $LDFLAGS | grep -q $lib
	if [ $? -ne 0 ] ; then
		LDFLAGS="-L$lib $LDFLAGS"
	fi
	fi
}

add_include()
{
	the_path=$1
	if [ -e $the_path ]; then
		if [ -z $C_INCLUDE_PATH ]; then
				C_INCLUDE_PATH=$the_path
		else
			echo $C_INCLUDE_PATH | grep -q $dir/include
			if [ $? -ne 0 ] ; then
				C_INCLUDE_PATH=$the_path:$C_INCLUDE_PATH
			fi
		fi
		if [ -z $CPLUS_INCLUDE_PATH ]; then
			CPLUS_INCLUDE_PATH=$the_path
		else
			echo $CPLUS_INCLUDE_PATH | grep -q $dir/include
			if [ $? -ne 0 ] ; then
				CPLUS_INCLUDE_PATH=$path:$CPLUS_INCLUDE_PATH
			fi
		fi
	fi
}

my_setup()
{
	dir=$1
	if [ -e $dir ]; then
		
		#echo $dir found!
		add_lib $dir/lib
		add_lib $dir/lib64
		add_include $dir/include
		
		if [ -e $dir/bin ]; then
			echo $PATH | grep -q $dir/bin
			if [ $? -ne 0 ] ; then
				PATH=$dir/bin:$PATH
			fi
		fi
	fi
}

my_setup2 () 
{
	local name=$1
	local dir=$LOCAL_INSTALLDIR/$name/used
	my_setup $dir
	
}

my_setup $LOCAL_INSTALLDIR/openmpi/1.6
my_setup llvm
my_setup2 cmake
my_setup2 doxygen
my_setup2 gcc
my_setup2 gmp
my_setup2 gnuplot
my_setup2 GotoBLAS2
my_setup2 mpfr
my_setup2 mpc
my_setup2 ParaView
my_setup2 metis
my_setup2 parmetis
my_setup2 scons
my_setup2 hlibpro


# tbb
add_lib $HOME/local/tbb/used/lib/intel64/gcc4.4/
add_lib $HOME/local/tbb/used/lib/
add_include $HOME/local/tbb/used/include/

# boost
add_lib $HOME/local/boost/used/stage/lib/


# completion for bash (for bash only)
SHELLTYPE=`ps -o comm="" -p $$`
case "$SHELLTYPE" in
	*bash*) complete -W "all cmake doxygen gcc gmp gnuplot GotoBLAS2 Metis mpfr mpc OpenMPI ParaView ParMetis scons hlibpro tbb" -o default -o nospace uginstall
	;;
esac

export PATH
export C_INCLUDE_PATH	
export CPLUS_INCLUDE_PATH
export LD_RUN_PATH
export LD_LIBRARY_PATH
export LIBRARY_PATH
export LDFLAGS
