# included from ug_includes.cmake
if(OpenCL)
	IF(APPLE)
		MESSAGE(STATUS "Info: Found OpenCL: -framework OpenCL (Apple)")
		SET(OPENCL_FOUND YES)
		set(linkLibraries "${linkLibraries} -framework OpenCL")   
		add_definitions(-DOPENCL_AVAILABLE)
	ELSE(APPLE)
		INCLUDE ("${UG_ROOT_PATH}/cmake/FindOpenCL.cmake")	
		if(OPENCL_FOUND)
			MESSAGE(STATUS "Info: Found OpenCL. Inc: ${OPENCL_INCLUDE_DIRS}, lib: ${OPENCL_LIB_DIR}")
			include_directories(${OPENCL_INCLUDE_DIRS})
			set(linkLibraries ${linkLibraries} ${OPENCL_LIB_DIR})   
			add_definitions(-DOPENCL_AVAILABLE)
		else(OPENCL_FOUND)
			MESSAGE(FATAL_ERROR " OpenCL not found! Aborting.")
		endif(OPENCL_FOUND)
	ENDIF(APPLE)
endif(OpenCL)