#!/bin/bash
######################################################################
#                           cekon
#-------------------------------------------------------------------
# using SLURM
######################################################################

function UJS_Submit
{
	echo "Cluster: cekon. Scheduler: SLURM."
	if [ $nppn -ne 1 ]; then
		echo "cekon does not support nppn > 1. Aborting."
		exit
	fi
	if [ $((npe%nppn)) -ne 0 ]; then
		echo "npe=$npe is not dividable by nppn=$nppn"
		exit
	fi
		
	local SlurmWalltime=""
	if [ $walltime != "unlimited" ]; then
		SlurmWalltime=--time=$walltime
	fi

	local SlurmMail=""
	if [ $mail == true ]; then 
		if [ -z "$UGSUBMIT_EMAIL" ]; then
			echo "please set UGSUBMIT_EMAIL or specify email with -email. Aborting."
			exit
		fi

		SlurmNotification="never"
		if [ $mailStart == true ]; then
			SlurmNotification="BEGIN"
		fi
		if [ $mailEnd == true ]; then
			if [ $SlurmNotification == "never" ]; then
				SlurmNotification="END"
			else
				SlurmNotification="ALL"
			fi
		fi
		if [ $mailError == true ]; then
			if [ $SlurmNotification == "never" ]; then
				SlurmNotification="FAIL"
			else
				SlurmNotification="ALL"
			fi
		fi	 
		SlurmMail="--mail-user=$UGSUBMIT_EMAIL --mail-type=$SlurmNotification"
	fi

	commandline="salloc -n $npe $SlurmMail $SlurmWalltime --job-name=$jobname mpirun $executable $args"
	echo " command:      "$commandline >> info.txt

	if [ $test == true ]; then
		echo "ONLY testing - NOT executing."
		echo "Submit/Start: $commandline"
		return
	fi

	if [ $interactive == true ]; then	
		echo "[[ current cluster allocation"
		squeue
		echo "]] current cluster allocation"
		
		echo "Start: $commandline"
		
		$commandline | tee $outdir/job.output
		return=$?	
		if [ ! $return == 0 ]; then
			echo "ERROR: salloc returned $return. Job has NOT been started."
			exit
		fi
	else
		echo "Submit: $commandline"
		nohup $commandline > $outdir/job.output &
		sleep 1
		jobid=`cat job.output | sed -n 1p | sed 's/.* \([0-9]*\).*/\1/'`
		
		echo " ------------" >> info.txt
		echo "  scontrol show jobid $jobid" >> info.txt
		echo " ------------" >> info.txt
		scontrol show jobid $jobid >> info.txt
	fi
}


function UJS_GetOptions
{
	nppnmax=1
	pemax=92	
}

function UJS_Info
{
	echo "UGSUBMIT Info for CEKON:"
	echo "Max Cores Total: 92 (23 Nodes with 4 Cores Per Node)"
	echo "Memory on each node: 4 GB"
	echo "Using SLURM on cekon"
	if [ ! -z $1 ] && [ $1 == "all" ]; then
		echo "squeue -o \"%.7i %6C %6D %.50j %.10u %.8T %.10M %.10l %.6D %19R\""
		squeue -o "%.7i %6C %6D %.50j %.10u %.8T %.10M %.10l %.6D %19R"
	else
		echo "squeue -u $USER -o \"%.7i %6C %6D %.50j %.10u %.8T %.10M %.10l %.6D %19R\""
		squeue -u $USER -o "%.7i %6C %6D %.50j %.10u %.8T %.10M %.10l %.6D %19R"
	fi	
}

function UJS_Cancel
{
	echo "Using SLURM on cekon"
	if [ ! -z $1 ] && [ $1 == "all" ]; then
		echo "your jobs:"
		squeue -u $USER -o "%.7i %6C %6D %.50j %.10u %.8T %.10M %.10l %.6D %19R"
		echo " "
		read -p "Are you sure you want to cancel all your jobs (yes=j,J,y or Y) ? " -n 1 -r
		echo " "		
		if [[ $REPLY =~ ^[JjYy]$ ]]
		then			
		    scancel --user=$USER
		fi
		
	else
		scancel $1
	fi
}	