#!/bin/bash
######################################################################
#                           cesari
#-------------------------------------------------------------------
# using SLURM
######################################################################

function UJS_Submit
{
	echo "Cluster: cesari. Scheduler: SLURM."
	
	SlurmMail=""
	if [ $mail == true ]; then 
		if [ -z "$UGSUBMIT_EMAIL" ]; then
			echo "please set UGSUBMIT_EMAIL or specify email with -email. Aborting."
			exit
		fi

		SlurmNotification="never"
		if [ $mailStart == true ]; then
			SlurmNotification="BEGIN"
		fi
		if [ $mailEnd == true ]; then
			if [ $SlurmNotification == "never" ]; then
				SlurmNotification="END"
			else
				SlurmNotification="ALL"
			fi
		fi
		if [ $mailError == true ]; then
			if [ $SlurmNotification == "never" ]; then
				SlurmNotification="FAIL"
			else
				SlurmNotification="ALL"
			fi
		fi	 
		SlurmMail="--mail-user=$UGSUBMIT_EMAIL --mail-type=$SlurmNotification"
	fi

	commandline="salloc -n $npe $SlurmMail --job-name=$jobname mpirun $executable $args"
	echo " command:      "$commandline >> info.txt

	if [ $test == true ]; then
		echo "ONLY testing - NOT executing."
		echo "Submit/Start: $commandline"
		return
	fi

	if [ $interactive == true ]; then	
		echo "[[ current cluster allocation"
		squeue
		echo "]] current cluster allocation"
		
		echo "Start: $commandline"
		
		$commandline | tee $outdir/job.output
		return=$?	
		if [ ! $return == 0 ]; then
			echo "ERROR: salloc returned $return. Job has NOT been started."
			exit
		fi
	else
		echo "Submit: $commandline"
		nohup $commandline > $outdir/job.output &
		sleep 1
		jobid=`cat job.output | sed -n 1p | sed 's/salloc: Granted job allocation \([0-9]*\).*/\1/'`
	fi
}


function UJS_GetOptions
{
	nppnmax=20
	pemax=300	
}

function UJS_Info
{
	echo "UGSUBMIT Info for cesari:"
	echo "Max Cores Total: 520 (26 Nodes with 10 Dualcores Per Node)"
	echo "Using SLURM on cesari"
	echo "squeue -u $USER"
	squeue -u $USER	
}

function UJS_Cancel
{
	echo "Using SLURM on cesari"
	scancel $1
}