#!/bin/bash
######################################################################
#                     qsub on Hunter / HLRS (aprun)
#-------------------------------------------------------------------
######################################################################

function UJS_Submit
{
	UJS_GetOptions

	if [ $walltime == "unlimited" ]; then
		walltime=01:00:00
	fi

	if [ $((npe%nppn)) -ne 0 ]; then
		echo "NOTE: npe=$npe is not divisible by nppn=$nppn. rounding up"
	fi




	echo "Cluster: Vulcan(genoa). Scheduler: qsub"
	if [ $nppn -gt $nppnmaxSingleThread ]; then
		qsubrun="mpirun --map-by core --bind-to core -np $npe -- $executable $args"
		# qsub doesn't know about hyper-threading. Only specify used procs. Round up.
		# nppnRaw=$(((nppn+1)/2))
	else
		qsubrun="mpirun --map-by core --bind-to core -np $npe -- $executable $args"
		# nppnRaw=$((nppn))
	fi
	PBSnodes="-l select=$nnodes:node_type=genoa:mpiprocs=$nppn"





	if [ -z "$queue" ]; then
		qsubqueue=""
	else
		qsubqueue="-q $queue"
	fi

	if [ $exclusive == true ]; then
		echo "WARNING: Exclusive not yet supported on this machine."
	fi


	pbsMail=""
	if [ $mail == true ]; then
		if [ -z "$UGSUBMIT_EMAIL" ]; then
			echo "please set UGSUBMIT_EMAIL or specify email with -email".
			exit
		fi
		pbsMail="-M $UGSUBMIT_EMAIL -m $pbsMailtype"
	fi

	# interactive: qsub -IX -l walltime=00:50:00 -l mppwidth=4 -l mppnppn=4

	qsubargs="$qsubqueue -v UG4_ROOT -N $jobname -o job.output -e job.error -j oe -l walltime=$walltime $PBSnodes $pbsMail"

  qmodules="module load gcc/15.2.0; module load openmpi/5.0.9-gcc-15.2.0; module load mkl/2025.2;"

	echo "echo \"cd $outdir; $qmodules; module list &> loaded_modules; $qsubrun \" | qsub $qsubargs" >> info.txt

	if [ $test == true ]; then
		echo "ONLY testing - NOT executing."
		return
	fi





	if [ $interactive == true ]; then
		echo "Interactive mode currently not supported on vulcan. Aborting."
	else
		jobid=`echo "cd $outdir; $qsubrun" | qsub $qsubargs` # actual execution
		return=$?
		if [ ! $return == 0 ]; then
			echo "ERROR: qsub returned $return. Job has NOT been scheduled."
			exit
		fi
		jobid=`echo $jobid | sed 's/\([0-9]*\).*/\1/'`
	fi
}



function UJS_GetOptions
{
	if [ $UGSUBMIT_TYPE == "Vulcan" ] || [ $UGSUBMIT_TYPE == "vulcan" ]; then
		    nppnmax=64 # 2*32 core (AMD Epyc 9334)
        pemax=3840  # 60 Nodes * 64 Cores per Node
        nppnmaxSingleThread=64
	else
		echo "WARNING: Unknown platform. guessed default values for MaxNumProcsPerNode (nppnmax) and MaxProcs (pemax) may be wrong."
		nppnmax=64 # 2 x AMD EPYC 9374F = 2 * 64 Cores
		pemax=3840 # 256 CPU-Nodes * 128 Cores per Node
		nppnmaxSingleThread=64
	fi
}

function UJS_Info
{
	echo "Using $UGSUBMIT_TYPE"
	echo "qstat -u $USER"
	qstat -u $USER
}


function UJS_Cancel
{
	echo "Using $UGSUBMIT_TYPE"
	echo "qdel $1"
	qdel $1
}
